### ISSUE TITLE
bug: urlencoded param causes api calls to throw error in frontends

### ISSUE THREAD

**Issue by anuraglol** [0xMukesh/hacky-node-template#5]
remove that and add cors...

**Comment by 0xMukesh** [comment]
1. There would be issues while parsing `string` and `array` parameters which are sent in the request payload. Check out this answer regarding this -- https://stackoverflow.com/a/51844327
2. Adding the CORS middleware is pretty simple. Check out this example on how to configure and use the `cors` package -- https://www.npmjs.com/package/cors#simple-usage-enable-all-cors-requests

**Comment by anuraglol** [comment]
👍
